### PR TITLE
feat/improve-nanny-logging

### PR DESCRIPTION
**Pull request by Thomas-95IS**
## Description

Includes:

* Write `WARNING` messages to log if Gateway raises an error.
* Fix writing 3 messages to console in local development work.
* Remove redundant `'Starting new HTTP connection (1): 127.0.0.1'` logs.

## Todo's before PR

- [ ] Branch has been rebased against develop
- [ ] Unit tests passed (`make test`)
- [ ] Selenium tests have passed
- [x] PR named appropriately - see [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [x] PR description describes the overall goals of PR commits
- [ ] Templates have been checked against the relevant user-story

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [x] Specified reviewers (even if it's yourself)
- [x] Specified assignees (those who'll merge)
- [x] Specified labels

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [ ] Should be merged?
- [x] Should be rebased?
- [ ] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

### CODE REVIEW

**Comment by Thomas-95IS** [comment]
_"85 failed tests"_ - whoops.

**Comment by ricaduchateau** [comment]
Hi @Thomas-95IS, looks like there are two more tests failing.

**Comment by Thomas-95IS** [comment]
rerun jenkins build

**Comment by Thomas-95IS** [comment]
Hi @ricaduchateau, this is ready for re-review.

If you could point out anything that's particularly confusing, that'd be very helpful (I'm not convinced everything here is totally intuitive).

**Pull request merged**
