### PR TITLE
CCN3-1038: Update send_email method to accept service_name parameter

### PR DESCRIPTION
**Pull request by ricaduchateau**
## Description

Update send_email method to accept service_name parameter and refactor views using this method

## Todo's before PR

- [x] Branch has been rebased against develop
- [x] Unit tests passed (`make test`)
- [x] PR named appropriately - see [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [x] PR description describes the overall goals of PR commits

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [x] Specified reviewers (even if it's yourself)
- [x] Specified assignees (those who'll merge)
- [x] Specified labels

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [x] Should be merged?
- [ ] Should be rebased?
- [ ] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

### CODE REVIEW

**Comment by ricaduchateau** [comment]
rerun jenkins build

**Comment by kingainformed** [comment]
Hi @ricaduchateau, does it make sense to add service name as an argument to the send email function? Within the Nanny application, I think you can just assume that it will always be set to "Nannies" and send that as a parameter to the Notify Gateway regardless.

**Comment by ricaduchateau** [comment]
Hi @kingainformed I see what you mean. I can take out the service_name argument and leave it in the request dictionary in the send_email method

**Comment by ricaduchateau** [comment]
rerun jenkins build

**Pull request merged**
